### ISSUE TITLE
PATCH request to endpoints served by grpc-gateway getting connection reset by peer

### ISSUE THREAD

**Issue by tegarajipangestu** [rookie-ninja/rk-grpc#80]
I am getting connection reset by peer when requesting to PATCH endpoints served by rk-grpc (with enableRkGwOption enabled)
```
 curl -vvv --location --request PATCH 'localhost:3000/v1/experiment/7' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data-raw '{
  "name": "Experiment model 123"
}'
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> PATCH /v1/experiment/7 HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.81.0
> Content-Type: application/json
> Accept: application/json
> Content-Length: 36
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```
By default, enabling enableRkGwOption in your project will result in grpc endpoints and rest endpoints served in the same port using cmux as multiplexer. This is where the bug comes because cmux does not recognize PATCH HTTP methods in their default HTTP method. (https://github.com/soheilhy/cmux/blob/v0.1.5/matchers.go#L46-L55)

There are two possible solutions:

1. Serving different port for gRPC and REST API (configurable in yml file)
2. Adding PATCH method in boot/grpc_entry.go file so cmux recognize PATCH method:
```
httpL := tcpL.Match(cmux.HTTP1Fast("PATCH"))
```

**Comment by dongxuny** [comment]
@tegarajipangestu Hi, it is definitely a bug in rk-grpc. Currently, I prefer the second option. I will review the implementation of fix this bug ASAP

**Comment by dongxuny** [comment]
https://github.com/rookie-ninja/rk-grpc/pull/81

**Comment by dongxuny** [comment]
v2.2.4 has been released with bug fix. @tegarajipangestu

**Comment by tegarajipangestu** [comment]
great, thanks for responding promptly @dongxuny!
